2022-02-16 00:45:35,398 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Loading settings from /home/ai-interns-jan22/.config/wandb/settings
2022-02-16 00:45:35,399 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Loading settings from /mnt/arshpreet/task1-fairface-dataset/wandb/settings
2022-02-16 00:45:35,399 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-16 00:45:35,399 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-16 00:45:35,400 INFO    MainThread:26163 [wandb_init.py:_log_setup():386] Logging user logs to /mnt/arshpreet/task1-fairface-dataset/wandb/run-20220216_004535-2lgmnrij/logs/debug.log
2022-02-16 00:45:35,400 INFO    MainThread:26163 [wandb_init.py:_log_setup():387] Logging internal logs to /mnt/arshpreet/task1-fairface-dataset/wandb/run-20220216_004535-2lgmnrij/logs/debug-internal.log
2022-02-16 00:45:35,400 INFO    MainThread:26163 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f88893b4320>
2022-02-16 00:45:35,405 INFO    MainThread:26163 [wandb_init.py:init():420] calling init triggers
2022-02-16 00:45:35,405 INFO    MainThread:26163 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-02-16 00:45:35,405 INFO    MainThread:26163 [wandb_init.py:init():442] re-initializing run, found existing run on stack: 2nqoso2t
2022-02-16 00:45:35,409 INFO    MainThread:26163 [wandb_run.py:finish():1468] finishing run arshpreet/FairFaceClassification/2nqoso2t
2022-02-16 00:45:35,412 INFO    MainThread:26163 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-16 00:45:35,419 INFO    MainThread:26163 [wandb_run.py:_restore():1769] restore
2022-02-16 00:45:40,817 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: None
2022-02-16 00:45:40,921 INFO    MainThread:26163 [wandb_run.py:_restore():1769] restore
2022-02-16 00:45:40,983 ERROR   MainThread:26163 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1805, in _atexit_cleanup
    self._on_finish()
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1988, in _on_finish
    self._poll_exit_response = self._wait_for_finish()
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1928, in _wait_for_finish
    poll_exit_resp = self._backend.interface.communicate_poll_exit()
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 586, in communicate_poll_exit
    resp = self._communicate_poll_exit(poll_exit)
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 402, in _communicate_poll_exit
    result = self._communicate(rec)
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 450, in init
    self._wl._global_run_stack[-1].finish()
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1474, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1814, in _atexit_cleanup
    self._backend.cleanup()
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/backend/backend.py", line 248, in cleanup
    self.interface.join()
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/mnt/arshpreet/env/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-02-16 00:45:56,395 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Loading settings from /home/ai-interns-jan22/.config/wandb/settings
2022-02-16 00:45:56,395 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Loading settings from /mnt/arshpreet/task1-fairface-dataset/wandb/settings
2022-02-16 00:45:56,395 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-16 00:45:56,395 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-16 00:45:56,395 INFO    MainThread:26163 [wandb_init.py:_log_setup():386] Logging user logs to /mnt/arshpreet/task1-fairface-dataset/wandb/run-20220216_004556-3n0kc2of/logs/debug.log
2022-02-16 00:45:56,395 INFO    MainThread:26163 [wandb_init.py:_log_setup():387] Logging internal logs to /mnt/arshpreet/task1-fairface-dataset/wandb/run-20220216_004556-3n0kc2of/logs/debug-internal.log
2022-02-16 00:45:56,396 INFO    MainThread:26163 [wandb_init.py:init():420] calling init triggers
2022-02-16 00:45:56,396 INFO    MainThread:26163 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-02-16 00:45:56,396 INFO    MainThread:26163 [wandb_init.py:init():442] re-initializing run, found existing run on stack: 2nqoso2t
2022-02-16 00:45:56,398 INFO    MainThread:26163 [wandb_run.py:finish():1468] finishing run arshpreet/FairFaceClassification/2nqoso2t
2022-02-16 00:45:56,401 INFO    MainThread:26163 [wandb_init.py:init():471] starting backend
2022-02-16 00:45:56,401 INFO    MainThread:26163 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-16 00:45:56,403 INFO    MainThread:26163 [backend.py:ensure_launched():219] starting backend process...
2022-02-16 00:45:56,512 INFO    MainThread:26163 [backend.py:ensure_launched():225] started backend process with pid: 1026
2022-02-16 00:45:56,515 INFO    MainThread:26163 [wandb_init.py:init():480] backend started and connected
2022-02-16 00:45:56,550 INFO    MainThread:26163 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-16 00:45:56,550 INFO    MainThread:26163 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-16 00:45:56,550 INFO    MainThread:26163 [wandb_init.py:init():550] updated telemetry
2022-02-16 00:45:56,747 INFO    MainThread:26163 [wandb_init.py:init():581] communicating current version
2022-02-16 00:45:58,061 INFO    MainThread:26163 [wandb_init.py:init():586] got version response 
2022-02-16 00:45:58,062 INFO    MainThread:26163 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-16 00:45:58,395 INFO    MainThread:26163 [wandb_init.py:init():624] starting run threads in backend
2022-02-16 00:45:58,476 INFO    MainThread:26163 [wandb_run.py:_console_start():1827] atexit reg
2022-02-16 00:45:58,478 INFO    MainThread:26163 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-16 00:45:58,478 INFO    MainThread:26163 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-16 00:45:58,480 INFO    MainThread:26163 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-16 00:45:58,480 INFO    MainThread:26163 [wandb_init.py:init():651] run started, returning control to user process
2022-02-16 00:55:47,589 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Loading settings from /home/ai-interns-jan22/.config/wandb/settings
2022-02-16 00:55:47,589 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Loading settings from /mnt/arshpreet/task1-fairface-dataset/wandb/settings
2022-02-16 00:55:47,589 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-16 00:55:47,589 INFO    MainThread:26163 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-16 00:55:47,589 INFO    MainThread:26163 [wandb_init.py:_log_setup():386] Logging user logs to /mnt/arshpreet/task1-fairface-dataset/wandb/run-20220216_005547-7vo7qcd3/logs/debug.log
2022-02-16 00:55:47,590 INFO    MainThread:26163 [wandb_init.py:_log_setup():387] Logging internal logs to /mnt/arshpreet/task1-fairface-dataset/wandb/run-20220216_005547-7vo7qcd3/logs/debug-internal.log
2022-02-16 00:55:47,590 INFO    MainThread:26163 [wandb_init.py:init():420] calling init triggers
2022-02-16 00:55:47,590 INFO    MainThread:26163 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-02-16 00:55:47,590 INFO    MainThread:26163 [wandb_init.py:init():442] re-initializing run, found existing run on stack: 3n0kc2of
2022-02-16 00:55:47,592 INFO    MainThread:26163 [wandb_run.py:finish():1468] finishing run arshpreet/FairFaceClassification/3n0kc2of
2022-02-16 00:55:47,593 INFO    MainThread:26163 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-16 00:55:47,595 INFO    MainThread:26163 [wandb_run.py:_restore():1769] restore
2022-02-16 00:55:48,206 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1107
  total_bytes: 1107
}

2022-02-16 00:55:48,325 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1107
  total_bytes: 1107
}

2022-02-16 00:55:48,655 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1107
  total_bytes: 1107
}

2022-02-16 00:55:48,830 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1107
  total_bytes: 3347
}

2022-02-16 00:55:48,936 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1107
  total_bytes: 3347
}

2022-02-16 00:55:49,040 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1107
  total_bytes: 3347
}

2022-02-16 00:55:49,148 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 1107
  total_bytes: 3347
}

2022-02-16 00:55:49,252 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3347
  total_bytes: 3347
}

2022-02-16 00:55:49,358 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3347
  total_bytes: 3347
}

2022-02-16 00:55:49,462 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3347
  total_bytes: 3347
}

2022-02-16 00:55:49,566 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3347
  total_bytes: 3347
}

2022-02-16 00:55:49,672 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3347
  total_bytes: 3347
}

2022-02-16 00:55:49,777 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3347
  total_bytes: 3347
}

2022-02-16 00:55:49,881 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3347
  total_bytes: 3347
}

2022-02-16 00:55:50,685 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3347
  total_bytes: 3347
}

2022-02-16 00:55:51,354 INFO    MainThread:26163 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 3347
  total_bytes: 3347
}
local_info {
}

2022-02-16 00:55:52,587 INFO    MainThread:26163 [wandb_run.py:_append_files():2194] logging synced files
2022-02-16 00:55:52,598 INFO    MainThread:26163 [wandb_init.py:init():471] starting backend
2022-02-16 00:55:52,598 INFO    MainThread:26163 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-16 00:55:52,600 INFO    MainThread:26163 [backend.py:ensure_launched():219] starting backend process...
2022-02-16 00:55:52,707 INFO    MainThread:26163 [backend.py:ensure_launched():225] started backend process with pid: 1275
2022-02-16 00:55:52,708 INFO    MainThread:26163 [wandb_init.py:init():480] backend started and connected
2022-02-16 00:55:52,743 INFO    MainThread:26163 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-16 00:55:52,743 INFO    MainThread:26163 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-16 00:55:52,743 INFO    MainThread:26163 [wandb_init.py:init():550] updated telemetry
2022-02-16 00:55:52,937 INFO    MainThread:26163 [wandb_init.py:init():581] communicating current version
2022-02-16 00:55:54,254 INFO    MainThread:26163 [wandb_init.py:init():586] got version response 
2022-02-16 00:55:54,255 INFO    MainThread:26163 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-16 00:55:54,577 INFO    MainThread:26163 [wandb_init.py:init():624] starting run threads in backend
2022-02-16 00:55:54,659 INFO    MainThread:26163 [wandb_run.py:_console_start():1827] atexit reg
2022-02-16 00:55:54,660 INFO    MainThread:26163 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-16 00:55:54,661 INFO    MainThread:26163 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-16 00:55:54,663 INFO    MainThread:26163 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-16 00:55:54,663 INFO    MainThread:26163 [wandb_init.py:init():651] run started, returning control to user process
